# DO NOT EDIT THIS LINE.
# The value will is changed automatically by our GitHub Actions workflows when preparing a new patch.
GAMEVERSION = '0.0'

# List of scripts to be loaded by ScriptLoader.rb. Adjust as needed.
SCRIPTS = [
  'Settings',

  'Technical/Debugging/PBDebug',
  'Technical/Debugging/DebugConsole',
  'Technical/Debugging/Errors',
  'Technical/Debugging/Validation',
  'Technical/Debugging/Deprecation',
  'Technical/MKXPCompatibility',
  'Technical/Files/FileTests',
  'Technical/Files/FileMixins',
  'Technical/Files/HTTPUtilities',
  'Technical/RubyUtilities',
  'Technical/IntlMessages',
  'Technical/Input',
  'Technical/PluginManager',
  'Technical/RPGSprite',

  'BattleSettings',

  'Save data/SaveData',
  'Save data/SaveDataValue',
  'Save data/SaveDataConversion',
  'Save data/GameSaveValues',
  'Save data/GameSaveConversions',

  'Game processing/StartGame',
  'Game processing/SceneMap',
  'Game processing/Interpreter',
  'Game processing/InterpreterCommands',
  'Game processing/EventHandlers',
  'Game processing/EventHandlerCollections',

  'Game classes/GameScreen',
  'Game classes/Switches and Variables/GameTemp',
  'Game classes/Switches and Variables/GameSwitches',
  'Game classes/Switches and Variables/GameVariables',
  'Game classes/Switches and Variables/GameSelfSwitches',
  'Game classes/GameSystem',
  'Game classes/GamePicture',
  'Game classes/GameMap',
  'Game classes/GameMapFactory',

  'Battle/Charms/Amulet',

  'Game classes/GameCharacter',
  'Game classes/GameEvent',
  'Game classes/GamePlayer',
  'Game classes/GameCommonEvent',
  'Game classes/GameFollower',
  'Game classes/GameFollowerFactory',
  'Game classes/GameStats',

  'Sprites/SpritePicture',
  'Sprites/SpriteTimer',
  'Sprites/SpriteCharacter',
  'Sprites/SpriteReflection',
  'Sprites/SpriteSurfBase',
  'Sprites/SpritesetGlobal',
  'Sprites/SpritesetMap',
  'Sprites/SpriteAnimationSprite',
  'Sprites/SpriteDynamicShadows',
  'Sprites/PictureEx',
  'Sprites/ScreenPosHelper',

  'Map renderer/TilemapRenderer',
  'Map renderer/TilesetWrapper',
  'Map renderer/AutotileExpander',
  'Map renderer/TileDrawingHelper',

  'Objects and windows/RPGCache',
  'Objects and windows/MessageConfig',
  'Objects and windows/Window',
  'Objects and windows/SpriteWindow',
  'Objects and windows/SpriteWindowtext',
  'Objects and windows/SpriteWindowpictures',
  'Objects and windows/BitmapSprite',
  'Objects and windows/AnimatedBitmap',
  'Objects and windows/Planes',
  'Objects and windows/DrawText',
  'Objects and windows/Messages',
  'Objects and windows/TextEntry',

  'Audio/Audio',
  'Audio/AudioPlay',

  'Scenes/Transitions',
  'Scenes/EventScene',

  'Data/GameData',

  'Data/Hardcoded data/GrowthRate',
  'Data/Hardcoded data/GenderRatio',
  'Data/Hardcoded data/EggGroup',
  'Data/Hardcoded data/BodyShape',
  'Data/Hardcoded data/BodyColor',
  'Data/Hardcoded data/Habitat',
  'Data/Hardcoded data/Evolution',
  'Data/Hardcoded data/Stat',
  'Data/Hardcoded data/Nature',
  'Data/Hardcoded data/Status',
  'Data/Hardcoded data/TerrainTag',
  'Data/Hardcoded data/Weather',
  'Data/Hardcoded data/EncounterType',
  'Data/Hardcoded data/Environment',
  'Data/Hardcoded data/BattleWeather',
  'Data/Hardcoded data/BattleTerrain',
  'Data/Hardcoded data/Target',

  'Data/PBS data/MiscPBSData',
  'Data/PBS data/TownMap',
  'Data/PBS data/Type',
  'Data/PBS data/Ability',
  'Data/PBS data/Move',
  'Data/PBS data/Item',
  'Data/PBS data/BerryPlant',
  'Data/PBS data/Species',
  'Data/PBS data/Speciesfiles',
  'Data/PBS data/SpeciesMetrics',
  'Data/PBS data/ShadowPokemon',
  'Data/PBS data/Ribbon',
  'Data/PBS data/Encounter',
  'Data/PBS data/TrainerType',
  'Data/PBS data/Trainer',
  'Data/PBS data/Metadata',
  'Data/PBS data/PlayerMetadata',
  'Data/PBS data/MapMetadata',
  'Data/PBS data/DungeonTileset',
  'Data/PBS data/DungeonParameters',
  'Data/PBS data/PhoneMessage',
  'Data/PBS data/BombasticCharms',

  'Battle/Battle/Battle',
  'Battle/Battle/BattleStartAndEnd',
  'Battle/Battle/BattleExpAndMoveLearning',
  'Battle/Battle/BattleActionAttacksPriority',
  'Battle/Battle/BattleActionSwitching',
  'Battle/Battle/BattleActionUseItem',
  'Battle/Battle/BattleActionRunning',
  'Battle/Battle/BattleActionOther',
  'Battle/Battle/BattleCommandPhase',
  'Battle/Battle/BattleAttackPhase',
  'Battle/Battle/BattleEndOfRoundPhase',
  'Battle/Battler/BattleBattler',
  'Battle/Battler/BattlerInitialize',
  'Battle/Battler/BattlerChangeSelf',
  'Battle/Battler/BattlerStatuses',
  'Battle/Battler/BattlerStatStages',
  'Battle/Battler/BattlerAbilityAndItem',
  'Battle/Battler/BattlerUseMove',
  'Battle/Battler/BattlerUseMoveTargeting',
  'Battle/Battler/BattlerUseMoveSuccessChecks',
  'Battle/Battler/BattlerUseMoveTriggerEffects',

  'Battle/Move/BattleMove',
  'Battle/Move/MoveUsage',
  'Battle/Move/MoveUsageCalculations',
  'Battle/Move/MoveBaseEffects',
  'Battle/Move/MoveEffectsMisc',
  'Battle/Move/MoveEffectsBattlerStats',
  'Battle/Move/MoveEffectsBattlerOther',
  'Battle/Move/MoveEffectsMoveAttributes',
  'Battle/Move/MoveEffectsMultiHit',
  'Battle/Move/MoveEffectsHealing',
  'Battle/Move/MoveEffectsItems',
  'Battle/Move/MoveEffectsChangeMoveEffect',
  'Battle/Move/MoveEffectsSwitchingActing',

  'Battle/Scene/BattleScene',
  'Battle/Scene/SceneInitialize',
  'Battle/Scene/SceneChooseCommands',
  'Battle/Scene/ScenePlayAnimations',
  'Battle/Scene/BattleSceneMenus',
  'Battle/Scene/BattleSceneObjects',
  'Battle/Scene/BattleSceneBaseAnimation',
  'Battle/Scene/BattleSceneAnimations',
  'Battle/Scene/BattleDebugScene',

  'Battle/AI/BattleAI',
  'Battle/AI/AISwitch',
  'Battle/AI/AIUseItem',
  'Battle/AI/AIMegaEvolve',
  'Battle/AI/AIChooseMove',
  'Battle/AI/AIChooseMoveGenericEffects',
  'Battle/AI/AIChooseMoveOtherScores',
  'Battle/AI/AIUtilities',
  'Battle/AI/AITrainer',
  'Battle/AI/AIBattler',
  'Battle/AI/AIMove',

  'Battle/AI MoveEffects/AIMoveEffectsMisc',
  'Battle/AI MoveEffects/AIMoveEffectsBattlerStats',
  'Battle/AI MoveEffects/AIMoveEffectsBattlerOther',
  'Battle/AI MoveEffects/AIMoveEffectsMoveAttributes',
  'Battle/AI MoveEffects/AIMoveEffectsMultiHit',
  'Battle/AI MoveEffects/AIMoveEffectsHealing',
  'Battle/AI MoveEffects/AIMoveEffectsItems',
  'Battle/AI MoveEffects/AIMoveEffectsChangeMoveEffect',
  'Battle/AI MoveEffects/AIMoveEffectsSwitchingActing',

  'Battle/Other battle code/PBEffects',
  'Battle/Other battle code/BattleActiveField',
  'Battle/Other battle code/BattleDamageState',
  'Battle/Other battle code/BattlePeers',
  'Battle/Other battle code/BattleCatchAndStoreMixin',
  'Battle/Other battle code/BattleClauses',
  'Battle/Other battle code/BattleAnimationPlayer',
  'Battle/Other battle code/BattleAbilityEffects',
  'Battle/Other battle code/BattleItemEffects',
  'Battle/Other battle code/BattlePokeBallEffects',
  'Battle/Other battle types/SafariBattle',
  'Battle/Other battle types/BugContestBattle',
  'Battle/Other battle types/BattlePalaceBattle',
  'Battle/Other battle types/BattleArenaBattle',
  'Battle/Other battle types/RecordedBattle',

  'Overworld/Overworld visuals/OverworldWeather',
  'Overworld/Overworld visuals/OverworldOverlays',
  'Overworld/Overworld visuals/OverworldMapTransitionAnims',
  'Overworld/Overworld',

  'Overworld/Battle triggering/OverworldBattleStarting',
  'Overworld/Battle triggering/OverworldBattleIntroAnim',
  'Overworld/Battle triggering/OverworldWildEncounters',
  'Overworld/Battle triggering/OverworldEncounterModifiers',
  'Overworld/Battle triggering/OverworldRoamingPokemon',

  'Overworld/OverworldMetadata',
  'Overworld/OverworldTime',
  'Overworld/OverworldFieldMoves',
  'Overworld/OverworldFishing',
  'Overworld/OverworldBerryPlants',
  'Overworld/OverworldDayCare',
  'Overworld/OverworldRandomDungeons',

  'Items/ItemUtilities',
  'Items/ItemEffects',
  'Items/ItemBattleEffects',
  'Items/ItemPhone',
  'Items/ItemPokeRadar',
  'Items/ItemMail',
  'Items/ItemSprites',

  'Items/PokemonBag',

  'Pokemon/Pokemon-related/FormHandlers',
  'Pokemon/Pokemon-related/ShadowPokemonOther',
  'Pokemon/Pokemon-related/PokemonSprites',
  'Pokemon/Pokemon-related/PokemonStorage',

  'Pokemon/Pokemon',
  'Pokemon/PokemonMegaEvolution',
  'Pokemon/PokemonShadowPokemon',
  'Pokemon/PokemonMove',
  'Pokemon/PokemonOwner',

  'Trainers and player/Trainer',
  'Trainers and player/TrainerLoadAndNew',
  'Trainers and player/TrainerSprites',
  'Trainers and player/Player',
  'Trainers and player/PlayerPokedex',

  'UI/Non-interactive UI/UISplashesAndTitleScreen',
  'UI/Non-interactive UI/UIControls',
  'UI/Non-interactive UI/UIEggHatching',
  'UI/Non-interactive UI/UIEvolution',
  'UI/Non-interactive UI/UITrading',
  'UI/Non-interactive UI/UIHallOfFame',
  'UI/Non-interactive UI/UICredits',

  'UI/UIPauseMenu',
  'UI/UIPokedexMenu',
  'UI/UIPokedexMain',
  'UI/UIPokedexEntry',
  'UI/UIParty',
  'UI/UISummary',
  'UI/UIBag',
  'UI/UIPokegear',
  'UI/UIRegionMap',
  'UI/UIPhone',
  'UI/UIJukebox',
  'UI/UITrainerCard',
  'UI/UILoad',
  'UI/UISave',
  'UI/UIOptions',
  'UI/UIReadyMenu',
  'UI/UIPokemonStorage',
  'UI/UIItemStorage',
  'UI/UIPC',
  'UI/UIPokeMart',
  'UI/UIBattlePointShop',
  'UI/UIMoveRelearner',
  'UI/UIPurifyChamber',
  'UI/UIMysteryGift',
  'UI/UITextEntry',
  'UI/UICharms',

  'Minigames/MinigameDuel',
  'Minigames/MinigameTripleTriad',
  'Minigames/MinigameSlotMachine',
  'Minigames/MinigameVoltorbFlip',
  'Minigames/MinigameLottery',
  'Minigames/MinigameMining',
  'Minigames/MinigameTilePuzzles',

  'Alternate battle modes/Battle Frontier/ChallengeBattleChallenge',
  'Alternate battle modes/Battle Frontier/ChallengeData',
  'Alternate battle modes/Battle Frontier/ChallengeChooseFoes',
  'Alternate battle modes/Battle Frontier/ChallengeBattles',
  'Alternate battle modes/Battle Frontier/UIBattleSwap',
  'Alternate battle modes/SafariZone',
  'Alternate battle modes/Battle Frontier rules/ChallengeChallengeRules',
  'Alternate battle modes/Battle Frontier rules/ChallengeRulesets',
  'Alternate battle modes/Battle Frontier rules/ChallengeEntryRestrictions',
  'Alternate battle modes/Battle Frontier rules/ChallengeLevelAdjustment',
  'Alternate battle modes/Battle Frontier rules/ChallengeBattleRules',
  'Alternate battle modes/BugContest',
  'Alternate battle modes/Battle Frontier generator/ChallengeGeneratorData',
  'Alternate battle modes/Battle Frontier generator/ChallengeGeneratorPokemon',
  'Alternate battle modes/Battle Frontier generator/ChallengeGeneratorTrainers',
  'Alternate battle modes/Battle Frontier generator/ChallengeGeneratorBattleSim',

  'Utilities/Utilities',
  'Utilities/UtilitiesPokemon',
  'Utilities/UtilitiesBattleAudio',

  'Debug/Editor screens/EditorScreens',
  'Debug/Editor screens/EditorScreensTerrainTags',
  'Debug/Editor screens/EditorScreensMapConnections',
  'Debug/Editor screens/EditorScreensSpritePositioning',
  'Debug/EditorUtilities',
  'Debug/Animation editor/AnimEditorSceneElements',
  'Debug/Animation editor/AnimEditorControlsButtons',
  'Debug/Animation editor/AnimEditorInterpolation',
  'Debug/Animation editor/AnimEditorExportImport',
  'Debug/Animation editor/AnimEditorFunctions',
  'Debug/EditorDataTypes',
  'Debug/Debug menus/DebugMenus',
  'Debug/Debug menus/DebugMenuCommands',
  'Debug/Debug menus/DebugMenuExtraCode',
  'Debug/Debug menus/DebugBattleCommands',
  'Debug/Debug menus/DebugBattlePkmnCommands',
  'Debug/Debug menus/DebugBattleExtraCode',
  'Debug/Debug menus/DebugPokemonCommands',
  'Debug/Debug menus/DebugFilenameUpdater',
  'Debug/EditorListers',

  #'Audio/AudioCache',

  'Compiler/Compiler',
  'Compiler/CompilerCompilePBS',
  'Compiler/CompilerWritePBS',
  'Compiler/CompilerMapsAndEvents',
  
  'Main/Main'
]